### ISSUE TITLE
How to get the `paymasterUrl` and `bundlerUrl` ?

### ISSUE THREAD

**Issue by luislucena16** [defi-wonderland/hardhat-account-abstraction#68]
this process is not clear for me, in the docs you say that these values are required but I don't understand how I can get both. I'm attentive to your response! Thanks in advance!

cc @0xGorilla

**Comment by excaliborr** [comment]
Hey @luislucena16 we added a short quick start guide to clarify this its currently in PR #69 and should be merged shortly

**Comment by luislucena16** [comment]
hey @excaliborr ohh I see it! this in `dev` branch I will use it and I will comment you! thank you!

**Comment by luislucena16** [comment]
maybe I can open a branch to improve the docs a bit!

**Comment by excaliborr** [comment]
Yes we are just waiting one one more reviewer to get it merged to main, then you should see it in the main readme

**Comment by excaliborr** [comment]
The docs were updated as the PR was merged so I am closing this issue now if you have any other questions feel free to open another one!

**Comment by luislucena16** [comment]
hey @excaliborr nice!! sure, I have opened another PR to add some docs!
